apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probes-pod
  name: probes-pod
spec:
  containers:
    - name: c1
      image: busybox
      command:
        - sh
        - -c
        - echo "Intai Dorm C1" && sleep 15 && touch /tmp/readiness && touch /tmp/liveness && echo 'Am create fisierele C1' && sleep Infinity  
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/readiness
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/liveness
        initialDelaySeconds: 5
        periodSeconds: 5
    - name: c2
      image: busybox
      command:
        - sh
        - -c
        - echo "Intai Dorm C2" && sleep 15 && touch /tmp/readiness && touch /tmp/liveness && echo 'Am create fisierele C2' && sleep Infinity  
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/readiness
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/liveness
        initialDelaySeconds: 5
        periodSeconds: 5